Repository hardingadonis/ligevan, pull requests merged in 2024-09, with the labels that each got.

#5 Feature/implement workflows - Done
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/commit-msg-validation.yml
  .github/workflows/pr-validation.yml
Labels: enhancement

#6 [Feature] Implement database design to schemas
  backend/package.json
  backend/src/app.module.ts
  backend/src/schemas/book.schema.ts
  backend/src/schemas/book_detail.schema.ts
  backend/src/schemas/borrow_history.schema.ts
  backend/src/schemas/borrow_request.schema.ts
  backend/src/schemas/category.schema.ts
  backend/src/schemas/guest.schema.ts
  backend/src/schemas/librarian.schema.ts
  backend/yarn.lock
Labels: documentation, enhancement

#7 [Feature] Implement schemas
  backend/package.json
  backend/src/app.module.ts
  backend/src/schemas/book.schema.ts
  backend/src/schemas/book_detail.schema.ts
  backend/src/schemas/borrow_history.schema.ts
  backend/src/schemas/borrow_request.schema.ts
  backend/src/schemas/category.schema.ts
  backend/src/schemas/guest.schema.ts
  backend/src/schemas/librarian.schema.ts
  backend/yarn.lock
Labels: documentation, enhancement

#9 add: dump data backend
  database/.gitkeep
  database/bookish.Book Detail.json
  database/bookish.Book.json
  database/bookish.Borrow History.json
  database/bookish.Borrow Request.json
  database/bookish.Category.json
  database/bookish.Guest.json
  database/bookish.Librarian.json
Labels: documentation

#10 add: dump data backend
  database/.gitkeep
  database/bookish.Book Detail.json
  database/bookish.Book.json
  database/bookish.Borrow History.json
  database/bookish.Borrow Request.json
  database/bookish.Category.json
  database/bookish.Guest.json
  database/bookish.Librarian.json
Labels: documentation
