Repository hardingadonis/ligevan, pull requests merged in 2024-10, with the labels that each got.

#14 update: use `module-alias` for alias `@/`
  backend/package.json
  backend/src/main.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.json
  backend/yarn.lock
Labels: documentation, enhancement

#15 [Feature] create module for voucher
  backend/src/app.module.ts
  backend/src/schemas/book.schema.ts
  backend/src/schemas/book_detail.schema.ts
  backend/src/schemas/borrow_history.schema.ts
  backend/src/schemas/borrow_request.schema.ts
  backend/src/schemas/category.schema.ts
  backend/src/schemas/guest.schema.ts
  backend/src/schemas/librarian.schema.ts
  backend/src/schemas/voucher.schema.ts
  backend/src/vouchers/dto/voucher.dto.ts
  backend/src/vouchers/vouchers.controller.ts
  backend/src/vouchers/vouchers.module.ts
  backend/src/vouchers/vouchers.service.ts
Labels: enhancement

#16 [Feature] create module for voucher
  backend/src/app.module.ts
  backend/src/schemas/book.schema.ts
  backend/src/schemas/book_detail.schema.ts
  backend/src/schemas/borrow_history.schema.ts
  backend/src/schemas/borrow_request.schema.ts
  backend/src/schemas/category.schema.ts
  backend/src/schemas/guest.schema.ts
  backend/src/schemas/librarian.schema.ts
  backend/src/schemas/voucher.schema.ts
  backend/src/vouchers/dto/voucher.dto.ts
  backend/src/vouchers/vouchers.controller.ts
  backend/src/vouchers/vouchers.module.ts
  backend/src/vouchers/vouchers.service.ts
Labels: enhancement

#17 [Feature] implement authen for admin
  backend/src/domains/admins/admins.module.ts
  backend/src/domains/admins/admins.service.ts
  backend/src/domains/auth/admin/auth.admin.controller.ts
  backend/src/domains/auth/admin/auth.admin.module.ts
  backend/src/domains/auth/admin/auth.admin.service.ts
  backend/src/domains/auth/admin/dto/login.dto.ts
  backend/src/domains/auth/auth.guard.ts
  backend/src/domains/auth/auth.module.ts
  backend/src/domains/domains.module.ts
  backend/src/swagger/setup.ts
Labels: enhancement

#18 [Feature] implement authen for admin
  backend/src/domains/admins/admins.module.ts
  backend/src/domains/admins/admins.service.ts
  backend/src/domains/auth/admin/auth.admin.controller.ts
  backend/src/domains/auth/admin/auth.admin.module.ts
  backend/src/domains/auth/admin/auth.admin.service.ts
  backend/src/domains/auth/admin/dto/login.dto.ts
  backend/src/domains/auth/auth.guard.ts
  backend/src/domains/auth/auth.module.ts
  backend/src/domains/domains.module.ts
  backend/src/swagger/setup.ts
Labels: enhancement

#19 Merge from `dev`
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/commit-msg-validation.yml
  .github/workflows/pr-validation.yml
  LEARN.md
  README.md
  backend/README.md
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/domains/admins/admins.controller.ts
  backend/src/domains/admins/admins.module.ts
  backend/src/domains/admins/admins.service.ts
  backend/src/domains/admins/dto/admin.dto.ts
  backend/src/domains/auth/admin/auth.admin.controller.ts
  backend/src/domains/auth/admin/auth.admin.module.ts
  backend/src/domains/auth/admin/auth.admin.service.ts
  backend/src/domains/auth/admin/dto/login.dto.ts
  backend/src/domains/auth/auth.guard.ts
  backend/src/domains/auth/auth.module.ts
  backend/src/domains/domains.module.ts
  backend/src/domains/vouchers/dto/voucher.dto.ts
  backend/src/domains/vouchers/vouchers.controller.ts
  backend/src/domains/vouchers/vouchers.module.ts
  backend/src/domains/vouchers/vouchers.service.ts
  backend/src/main.ts
  backend/src/middlewares/morgan.middleware.ts
  backend/src/schemas/admin.schema.ts
  backend/src/schemas/voucher.schema.ts
  backend/src/swagger/setup.ts
  backend/src/utils/hash.util.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.json
  backend/yarn.lock
  docs/CONTRIBUTING.md
  frontend/README.md
  frontend/package.json
  package.json
  scripts/validate-branches-on-creation.sh
Labels: documentation, enhancement

#20 Feature: implement dockerize for backend
  .github/workflows/publish-backend-image.yml
  backend/.dockerignore
  backend/Dockerfile
  backend/README.md
  backend/package.json
  backend/src/main.ts
  backend/src/middlewares/morgan.middleware.ts
  backend/tsconfig.json
  backend/yarn.lock
  package.json
  scripts/get-version.sh
Labels: documentation, enhancement

#21 Feature: implement dockerize for frontend
  .editorconfig
  .github/workflows/publish-frontend-image.yml
  frontend/.dockerignore
  frontend/.editorconfig
  frontend/Dockerfile
Labels: documentation, enhancement

#24 [Feature] completed implement course api
  backend/src/domains/admins/admins.module.ts
  backend/src/domains/admins/admins.service.ts
  backend/src/domains/admins/dto/admin.dto.ts
  backend/src/domains/courses/courses.controller.ts
  backend/src/domains/courses/courses.module.ts
  backend/src/domains/courses/courses.service.ts
  backend/src/domains/courses/dto/course.dto.ts
  backend/src/domains/domains.module.ts
  backend/src/domains/vouchers/dto/voucher.dto.ts
  backend/src/domains/vouchers/vouchers.controller.ts
  backend/src/domains/vouchers/vouchers.module.ts
  backend/src/domains/vouchers/vouchers.service.ts
  backend/src/schemas/course.schema.ts
Labels: enhancement

#26 [Feature]completed implement for `centers` module
  backend/src/domains/centers/centers.controller.ts
  backend/src/domains/centers/centers.module.ts
  backend/src/domains/centers/centers.service.ts
  backend/src/domains/centers/dto/center.dto.ts
  backend/src/domains/courses/courses.service.ts
  backend/src/domains/domains.module.ts
  backend/src/domains/vouchers/vouchers.service.ts
  backend/src/schemas/center.schema.ts
Labels: enhancement

#27 [Feature] completed implement centers
  backend/src/domains/centers/centers.controller.ts
  backend/src/domains/centers/centers.module.ts
  backend/src/domains/centers/centers.service.ts
  backend/src/domains/centers/dto/center.dto.ts
  backend/src/domains/courses/courses.service.ts
  backend/src/domains/domains.module.ts
  backend/src/domains/vouchers/vouchers.service.ts
  backend/src/schemas/center.schema.ts
Labels: enhancement

#29 [Feature] implement api for teachers
  backend/src/domains/domains.module.ts
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/teachers/teachers.controller.ts
  backend/src/domains/teachers/teachers.module.ts
  backend/src/domains/teachers/teachers.service.ts
  backend/src/schemas/teachers.schema.ts
Labels: enhancement

#30 [Feature] implement api for teachers
  backend/src/domains/domains.module.ts
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/teachers/teachers.controller.ts
  backend/src/domains/teachers/teachers.module.ts
  backend/src/domains/teachers/teachers.service.ts
  backend/src/schemas/teachers.schema.ts
Labels: enhancement

#31 Merge from `dev`
  .editorconfig
  .github/workflows/publish-backend-image.yml
  .github/workflows/publish-frontend-image.yml
  .prettierrc
  backend/.dockerignore
  backend/.editorconfig
  backend/.prettierrc
  backend/Dockerfile
  backend/README.md
  backend/package.json
  backend/src/app.module.ts
  backend/src/domains/admins/admins.controller.ts
  backend/src/domains/admins/admins.module.ts
  backend/src/domains/admins/admins.service.ts
  backend/src/domains/admins/dto/admin.dto.ts
  backend/src/domains/auth/admin/auth.admin.controller.ts
  backend/src/domains/auth/admin/auth.admin.module.ts
  backend/src/domains/auth/admin/auth.admin.service.ts
  backend/src/domains/auth/auth.guard.ts
  backend/src/domains/auth/auth.module.ts
  backend/src/domains/centers/centers.controller.ts
  backend/src/domains/centers/centers.module.ts
  backend/src/domains/centers/centers.service.ts
  backend/src/domains/centers/dto/center.dto.ts
  backend/src/domains/courses/courses.controller.ts
  backend/src/domains/courses/courses.module.ts
  backend/src/domains/courses/courses.service.ts
  backend/src/domains/courses/dto/course.dto.ts
  backend/src/domains/domains.module.ts
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/teachers/teachers.controller.ts
  backend/src/domains/teachers/teachers.module.ts
  backend/src/domains/teachers/teachers.service.ts
  backend/src/domains/vouchers/dto/voucher.dto.ts
  backend/src/domains/vouchers/vouchers.controller.ts
  backend/src/domains/vouchers/vouchers.module.ts
  backend/src/domains/vouchers/vouchers.service.ts
  backend/src/main.ts
  backend/src/middlewares/morgan.middleware.ts
  backend/src/schemas/center.schema.ts
  backend/src/schemas/course.schema.ts
  backend/src/schemas/teachers.schema.ts
  backend/src/swagger/setup.ts
  backend/tsconfig.json
  backend/yarn.lock
  frontend/.dockerignore
  frontend/.editorconfig
  frontend/.prettierrc
  frontend/Dockerfile
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/main.tsx
  frontend/yarn.lock
  package.json
  scripts/get-version.sh
  yarn.lock
Labels: documentation, enhancement

#34 Feature/fix center chuong
  backend/src/domains/centers/centers.service.ts
  backend/src/domains/centers/dto/center.dto.ts
Labels: enhancement

#35 [Feature] update `centers` module
  backend/src/domains/centers/centers.service.ts
  backend/src/domains/centers/dto/center.dto.ts
Labels: help wanted

#37 Feature/implement class chuong
  backend/src/domains/classes/classes.controller.ts
  backend/src/domains/classes/classes.module.ts
  backend/src/domains/classes/classes.service.ts
  backend/src/domains/classes/dto/class.dto.ts
  backend/src/domains/domains.module.ts
Labels: enhancement

#38 [Feature] completed implement `class` api
  backend/src/domains/classes/classes.controller.ts
  backend/src/domains/classes/classes.module.ts
  backend/src/domains/classes/classes.service.ts
  backend/src/domains/classes/dto/class.dto.ts
  backend/src/domains/domains.module.ts
Labels: enhancement

#42 Feature/implement slot chuong
  backend/src/domains/domains.module.ts
  backend/src/domains/slots/dto/slot.dto.ts
  backend/src/domains/slots/slots.controller.ts
  backend/src/domains/slots/slots.module.ts
  backend/src/domains/slots/slots.service.ts
  backend/src/schemas/slot.schema.ts
Labels: enhancement

#40 Feature/implement student chuong
  backend/src/domains/domains.module.ts
  backend/src/domains/students/dto/student.dto.ts
  backend/src/domains/students/students.controller.ts
  backend/src/domains/students/students.module.ts
  backend/src/domains/students/students.service.ts
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/schemas/student.schema.ts
Labels: enhancement

#44 [Feature]completed implement `slot` api for issue #41
  backend/src/domains/domains.module.ts
  backend/src/domains/slots/dto/slot.dto.ts
  backend/src/domains/slots/slots.controller.ts
  backend/src/domains/slots/slots.module.ts
  backend/src/domains/slots/slots.service.ts
  backend/src/schemas/slot.schema.ts
Labels: enhancement

#45 [Feature] completed implement `student` api for issue #39
  backend/src/domains/domains.module.ts
  backend/src/domains/students/dto/student.dto.ts
  backend/src/domains/students/students.controller.ts
  backend/src/domains/students/students.module.ts
  backend/src/domains/students/students.service.ts
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/schemas/student.schema.ts
Labels: enhancement

#46 Feature/implement salary chuong
  backend/src/domains/domains.module.ts
  backend/src/domains/salaries/dto/salary.dto.ts
  backend/src/domains/salaries/salaries.controller.ts
  backend/src/domains/salaries/salaries.module.ts
  backend/src/domains/salaries/salaries.service.ts
Labels: enhancement

#47 [Feature] completed implement `salaries` api (create, update, getById, getAll)
  backend/src/domains/domains.module.ts
  backend/src/domains/salaries/dto/salary.dto.ts
  backend/src/domains/salaries/salaries.controller.ts
  backend/src/domains/salaries/salaries.module.ts
  backend/src/domains/salaries/salaries.service.ts
Labels: enhancement

#49 Feature/implement attendance chuong
  backend/src/domains/attendances/attendances.controller.ts
  backend/src/domains/attendances/attendances.module.ts
  backend/src/domains/attendances/attendances.service.ts
  backend/src/domains/attendances/dto/attendance.dto.ts
  backend/src/domains/domains.module.ts
Labels: enhancement

#50 [Feature] completed implement attendances api #48
  backend/src/domains/attendances/attendances.controller.ts
  backend/src/domains/attendances/attendances.module.ts
  backend/src/domains/attendances/attendances.service.ts
  backend/src/domains/attendances/dto/attendance.dto.ts
  backend/src/domains/domains.module.ts
Labels: enhancement

#52 Feature/implement payment chuong
  backend/src/domains/domains.module.ts
  backend/src/domains/payments/dto/payment.dto.ts
  backend/src/domains/payments/payments.controller.ts
  backend/src/domains/payments/payments.module.ts
  backend/src/domains/payments/payments.service.ts
Labels: enhancement

#53 [Feature] completed implement `payments` api (create, update, getById, getAll)
  backend/src/domains/domains.module.ts
  backend/src/domains/payments/dto/payment.dto.ts
  backend/src/domains/payments/payments.controller.ts
  backend/src/domains/payments/payments.module.ts
  backend/src/domains/payments/payments.service.ts
Labels: enhancement

#56 Optimize dto of modules
  backend/src/domains/attendances/dto/attendance.dto.ts
  backend/src/domains/centers/dto/center.dto.ts
  backend/src/domains/classes/dto/class.dto.ts
  backend/src/domains/courses/dto/course.dto.ts
  backend/src/domains/salaries/dto/salary.dto.ts
  backend/src/domains/slots/dto/slot.dto.ts
  backend/src/domains/students/dto/student.dto.ts
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/vouchers/dto/voucher.dto.ts
Labels: enhancement

#33 [Feature] implement `docker compose`
  README.md
  backend/README.md
  docker-compose.development.yml
  docker-compose.yml
  docs/USAGE.md
  frontend/README.md
Labels: enhancement

#57 Feature/optimize modules chuong
  backend/src/domains/admins/admins.controller.ts
  backend/src/domains/admins/admins.service.ts
  backend/src/domains/attendances/attendances.service.ts
  backend/src/domains/centers/centers.controller.ts
  backend/src/domains/centers/centers.service.ts
  backend/src/domains/classes/classes.service.ts
  backend/src/domains/courses/courses.controller.ts
  backend/src/domains/courses/courses.service.ts
  backend/src/domains/payments/payments.service.ts
  backend/src/domains/salaries/salaries.service.ts
  backend/src/domains/slots/slots.service.ts
  backend/src/domains/students/students.service.ts
  backend/src/domains/teachers/teachers.service.ts
  backend/src/domains/vouchers/vouchers.controller.ts
  backend/src/domains/vouchers/vouchers.service.ts
Labels: enhancement

#58 [Feature]optimize modules
  backend/src/domains/admins/admins.controller.ts
  backend/src/domains/admins/admins.service.ts
  backend/src/domains/attendances/attendances.service.ts
  backend/src/domains/attendances/dto/attendance.dto.ts
  backend/src/domains/centers/centers.controller.ts
  backend/src/domains/centers/centers.service.ts
  backend/src/domains/centers/dto/center.dto.ts
  backend/src/domains/classes/classes.service.ts
  backend/src/domains/classes/dto/class.dto.ts
  backend/src/domains/courses/courses.controller.ts
  backend/src/domains/courses/courses.service.ts
  backend/src/domains/courses/dto/course.dto.ts
  backend/src/domains/payments/payments.service.ts
  backend/src/domains/salaries/dto/salary.dto.ts
  backend/src/domains/salaries/salaries.service.ts
  backend/src/domains/slots/dto/slot.dto.ts
  backend/src/domains/slots/slots.service.ts
  backend/src/domains/students/dto/student.dto.ts
  backend/src/domains/students/students.service.ts
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/teachers/teachers.service.ts
  backend/src/domains/vouchers/dto/voucher.dto.ts
  backend/src/domains/vouchers/vouchers.controller.ts
  backend/src/domains/vouchers/vouchers.service.ts
Labels: enhancement

#60 [Feature] Login strategies
  backend/README.md
  backend/package.json
  backend/src/domains/admins/admins.controller.ts
  backend/src/domains/admins/admins.service.ts
  backend/src/domains/attendances/attendances.service.ts
  backend/src/domains/attendances/dto/attendance.dto.ts
  backend/src/domains/auth/admin/auth.admin.controller.ts
  backend/src/domains/auth/admin/auth.admin.module.ts
  backend/src/domains/auth/admin/auth.admin.service.ts
  backend/src/domains/auth/auth.controller.ts
  backend/src/domains/auth/auth.guard.ts
  backend/src/domains/auth/auth.module.ts
  backend/src/domains/auth/auth.service.ts
  backend/src/domains/auth/config/jwt.config.ts
  backend/src/domains/auth/dto/auth.admin.dto.ts
  backend/src/domains/auth/dto/auth.teacher.dto.ts
  backend/src/domains/auth/guards/admin.guard.ts
  backend/src/domains/auth/guards/jwt.guard.ts
  backend/src/domains/auth/guards/teacher.guard.ts
  backend/src/domains/auth/strategies/admin.strategy.ts
  backend/src/domains/auth/strategies/jwt.strategy.ts
  backend/src/domains/auth/strategies/teacher.strategy.ts
  backend/src/domains/centers/centers.controller.ts
  backend/src/domains/centers/centers.service.ts
  backend/src/domains/centers/dto/center.dto.ts
  backend/src/domains/classes/classes.service.ts
  backend/src/domains/classes/dto/class.dto.ts
  backend/src/domains/courses/courses.controller.ts
  backend/src/domains/courses/courses.service.ts
  backend/src/domains/courses/dto/course.dto.ts
  backend/src/domains/payments/payments.service.ts
  backend/src/domains/salaries/dto/salary.dto.ts
  backend/src/domains/salaries/salaries.service.ts
  backend/src/domains/slots/dto/slot.dto.ts
  backend/src/domains/slots/slots.service.ts
  backend/src/domains/students/dto/student.dto.ts
  backend/src/domains/students/students.service.ts
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/teachers/teachers.service.ts
  backend/src/domains/vouchers/dto/voucher.dto.ts
  backend/src/domains/vouchers/vouchers.controller.ts
  backend/src/domains/vouchers/vouchers.service.ts
  backend/yarn.lock
  frontend/package.json
  frontend/yarn.lock
Labels: documentation, enhancement

#61 [Feature] update: course ref by `class`
  backend/src/domains/classes/dto/class.dto.ts
  backend/src/schemas/class.schema.ts
Labels: enhancement

#63 [Feature] update: course ref by class
  backend/src/domains/classes/dto/class.dto.ts
  backend/src/schemas/class.schema.ts
Labels: enhancement

#62 add: implement base project in frontend
  frontend/src/assets/.gitkeep
  frontend/src/components/.gitkeep
  frontend/src/pages/.gitkeep
  frontend/src/services/api/.gitkeep
  frontend/src/utils/.gitkeep
Labels: enhancement

#64 update: update structure folder in frontend
  frontend/src/App.tsx
  frontend/src/assets/styles/global.css
  frontend/src/components/commons/Footer.tsx
  frontend/src/components/commons/Header.tsx
  frontend/src/components/commons/SIdebar.tsx
  frontend/src/layouts/admin.tsx
  frontend/src/layouts/student.tsx
  frontend/src/layouts/teacher.tsx
  frontend/src/pages/admin/Dashboard.tsx
  frontend/src/pages/admin/Login.tsx
  frontend/src/pages/student/Homepage.tsx
  frontend/src/pages/student/Login.tsx
  frontend/src/pages/teacher/Homepage.tsx
  frontend/src/pages/teacher/Login.tsx
  frontend/src/utils/encoding.ts
Labels: enhancement

#65 add: implement base project in frontend
  frontend/src/App.tsx
  frontend/src/assets/.gitkeep
  frontend/src/assets/styles/global.css
  frontend/src/components/commons/Footer.tsx
  frontend/src/components/commons/Header.tsx
  frontend/src/components/commons/SIdebar.tsx
  frontend/src/layouts/admin.tsx
  frontend/src/layouts/student.tsx
  frontend/src/layouts/teacher.tsx
  frontend/src/pages/admin/Dashboard.tsx
  frontend/src/pages/admin/Login.tsx
  frontend/src/pages/student/Homepage.tsx
  frontend/src/pages/student/Login.tsx
  frontend/src/pages/teacher/Homepage.tsx
  frontend/src/pages/teacher/Login.tsx
  frontend/src/services/api/.gitkeep
  frontend/src/utils/encoding.ts
Labels: enhancement

#66 add: implement login strategies with local & jwt
  backend/README.md
  backend/package.json
  backend/src/domains/auth/admin/auth.admin.controller.ts
  backend/src/domains/auth/admin/auth.admin.module.ts
  backend/src/domains/auth/admin/auth.admin.service.ts
  backend/src/domains/auth/auth.controller.ts
  backend/src/domains/auth/auth.guard.ts
  backend/src/domains/auth/auth.module.ts
  backend/src/domains/auth/auth.service.ts
  backend/src/domains/auth/config/jwt.config.ts
  backend/src/domains/auth/dto/auth.admin.dto.ts
  backend/src/domains/auth/dto/auth.teacher.dto.ts
  backend/src/domains/auth/guards/admin.guard.ts
  backend/src/domains/auth/guards/jwt.guard.ts
  backend/src/domains/auth/guards/teacher.guard.ts
  backend/src/domains/auth/strategies/admin.strategy.ts
  backend/src/domains/auth/strategies/jwt.strategy.ts
  backend/src/domains/auth/strategies/teacher.strategy.ts
  backend/src/domains/teachers/teachers.service.ts
  backend/yarn.lock
Labels: documentation, enhancement

#75 feat: implement cors for backend
  backend/README.md
  backend/src/app.module.ts
  backend/src/config/cors.config.ts
  backend/src/main.ts
Labels: documentation, enhancement

#73 add: add homepage for admin
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/pages/admin/Dashboard.tsx
  frontend/yarn.lock
Labels: documentation, enhancement

#76 add: home page for student
  frontend/src/App.tsx
  frontend/src/assets/.gitkeep
  frontend/src/assets/styles/header.css
  frontend/src/assets/styles/listCourse.css
  frontend/src/components/commons/Footer.tsx
  frontend/src/components/commons/Header.tsx
  frontend/src/components/student/CardCourse.tsx
  frontend/src/components/student/DropdownCenter.tsx
  frontend/src/components/student/Header.tsx
  frontend/src/components/student/ListCourse.tsx
  frontend/src/layouts/student/notLogin.tsx
  frontend/src/models/center.ts
  frontend/src/models/course.ts
  frontend/src/models/voucher.ts
  frontend/src/pages/student/Homepage.tsx
  frontend/src/services/api/.gitkeep
  frontend/src/services/getAllCenter.ts
  frontend/src/services/getAllCourse.ts
Labels: enhancement

#77 update: update brand name in footer
  frontend/src/components/commons/Footer.tsx
Labels: enhancement

#78 feat: implement #69
  backend/src/domains/auth/auth.controller.ts
  backend/src/domains/auth/auth.service.ts
  backend/src/domains/auth/decorators/roles.decorator.ts
  backend/src/domains/auth/enums/role.enum.ts
  backend/src/domains/auth/guards/roles.guard.ts
  backend/src/domains/auth/strategies/jwt.strategy.ts
Labels: documentation, enhancement

#79 feat: implement based-role authorized
  backend/src/domains/auth/auth.controller.ts
  backend/src/domains/auth/auth.service.ts
  backend/src/domains/auth/decorators/roles.decorator.ts
  backend/src/domains/auth/enums/role.enum.ts
  backend/src/domains/auth/guards/roles.guard.ts
  backend/src/domains/auth/strategies/jwt.strategy.ts
Labels: documentation, enhancement

#82 add: add lazy for loading route
  frontend/src/App.tsx
  frontend/src/components/student/CardCourse.tsx
  frontend/src/components/student/DropdownCenter.tsx
  frontend/src/components/student/ListCourse.tsx
  frontend/src/layouts/student/notLogin.tsx
  frontend/src/models/center.ts
  frontend/src/models/voucher.ts
  frontend/src/pages/student/Homepage.tsx
  frontend/src/schemas/admin.schema.ts
  frontend/src/schemas/attendance.schema.ts
  frontend/src/schemas/center.schema.ts
  frontend/src/schemas/class.schema.ts
  frontend/src/schemas/course.schema.ts
  frontend/src/schemas/payment.schema.ts
  frontend/src/schemas/salary.schema.ts
  frontend/src/schemas/slot.schema.ts
  frontend/src/schemas/student.schema.ts
  frontend/src/schemas/teacher.schema.ts
  frontend/src/schemas/voucher.schema.ts
  frontend/src/services/api/admin.ts
  frontend/src/services/api/attendance.ts
  frontend/src/services/api/center.ts
  frontend/src/services/api/class.ts
  frontend/src/services/api/course.ts
  frontend/src/services/api/payment.ts
  frontend/src/services/api/salary.ts
  frontend/src/services/api/slot.ts
  frontend/src/services/api/student.ts
  frontend/src/services/api/teacher.ts
  frontend/src/services/api/voucher.ts
  frontend/src/utils/apiBase.ts
Labels: enhancement

#84 add: setup slice base for store
  frontend/src/main.tsx
  frontend/src/slices/admin.ts
  frontend/src/slices/attendance.ts
  frontend/src/slices/center.ts
  frontend/src/slices/class.ts
  frontend/src/slices/course.ts
  frontend/src/slices/payment.ts
  frontend/src/slices/salary.ts
  frontend/src/slices/slot.ts
  frontend/src/slices/student.ts
  frontend/src/slices/teacher.ts
  frontend/src/slices/voucher.ts
  frontend/src/store.ts
Labels: enhancement

#85 update: format all schemas
  frontend/src/schemas/admin.schema.ts
  frontend/src/schemas/attendance.schema.ts
  frontend/src/schemas/center.schema.ts
  frontend/src/schemas/class.schema.ts
  frontend/src/schemas/course.schema.ts
  frontend/src/schemas/payment.schema.ts
  frontend/src/schemas/salary.schema.ts
  frontend/src/schemas/slot.schema.ts
  frontend/src/schemas/student.schema.ts
  frontend/src/schemas/teacher.schema.ts
  frontend/src/schemas/voucher.schema.ts
Labels: enhancement

#86 update: add avatar for `student`
  frontend/src/schemas/student.schema.ts
  frontend/src/services/api/center.ts
  frontend/src/services/api/course.ts
  frontend/vite.config.ts
Labels: enhancement

#88 feat: implement login with google for students
  backend/README.md
  backend/package.json
  backend/src/domains/auth/auth.controller.ts
  backend/src/domains/auth/auth.module.ts
  backend/src/domains/auth/auth.service.ts
  backend/src/domains/auth/config/google-oauth2.config.ts
  backend/src/domains/auth/enums/role.enum.ts
  backend/src/domains/auth/guards/student.guard.ts
  backend/src/domains/auth/strategies/student.strategy.ts
  backend/src/domains/students/dto/student.dto.ts
  backend/src/domains/students/students.service.ts
  backend/src/schemas/student.schema.ts
  backend/yarn.lock
Labels: documentation, enhancement

#89 [Feature] delete try catch for all services
  backend/src/domains/admins/admins.service.ts
  backend/src/domains/attendances/attendances.service.ts
  backend/src/domains/centers/centers.service.ts
  backend/src/domains/classes/classes.service.ts
  backend/src/domains/courses/courses.service.ts
  backend/src/domains/payments/payments.service.ts
  backend/src/domains/salaries/salaries.service.ts
  backend/src/domains/slots/slots.service.ts
  backend/src/domains/teachers/teachers.service.ts
  backend/src/domains/vouchers/vouchers.service.ts
Labels: enhancement

#90 feat: implement login with google for students
  backend/README.md
  backend/package.json
  backend/src/domains/auth/auth.controller.ts
  backend/src/domains/auth/auth.module.ts
  backend/src/domains/auth/auth.service.ts
  backend/src/domains/auth/config/google-oauth2.config.ts
  backend/src/domains/auth/enums/role.enum.ts
  backend/src/domains/auth/guards/student.guard.ts
  backend/src/domains/auth/strategies/student.strategy.ts
  backend/src/domains/students/dto/student.dto.ts
  backend/src/domains/students/students.service.ts
  backend/src/schemas/student.schema.ts
  backend/yarn.lock
Labels: documentation, enhancement

#94 [Feature]update populate for api get
  backend/src/domains/attendances/attendances.service.ts
  backend/src/domains/centers/centers.service.ts
  backend/src/domains/classes/classes.service.ts
  backend/src/domains/payments/payments.service.ts
  backend/src/domains/salaries/salaries.service.ts
  backend/src/domains/slots/slots.service.ts
  backend/src/domains/students/students.service.ts
  backend/src/domains/teachers/teachers.service.ts
Labels: enhancement

#96 update: api service for `student` & `teacher`
  backend/src/domains/students/students.service.ts
  backend/src/domains/teachers/teachers.service.ts
Labels: enhancement

#95 [Feature]update populate for api get
  backend/src/domains/attendances/attendances.service.ts
  backend/src/domains/centers/centers.service.ts
  backend/src/domains/classes/classes.service.ts
  backend/src/domains/payments/payments.service.ts
  backend/src/domains/salaries/salaries.service.ts
  backend/src/domains/slots/slots.service.ts
  backend/src/domains/students/students.service.ts
  backend/src/domains/teachers/teachers.service.ts
Labels: enhancement

#97 feat: enable tls support
  .gitignore
  docker-compose.development.yml
  docker-compose.yml
  proxy/.editorconfig
  proxy/nginx.conf
Labels: documentation, enhancement

#98 feat: implement proxy for https
  .gitignore
  docker-compose.development.yml
  docker-compose.yml
  proxy/.editorconfig
  proxy/nginx.conf
Labels: documentation, enhancement

#107 hotfix: fix login teacher
  .github/workflows/commit-msg-validation.yml
  backend/src/domains/teachers/teachers.service.ts
Labels: bug

#108 dev: release backend v1.1.1
  .github/workflows/commit-msg-validation.yml
  .github/workflows/validate-branches-on-creation.yml
  backend/package.json
  backend/src/domains/teachers/teachers.service.ts
  proxy/nginx.conf
Labels: bug, enhancement

#113 [Feature]add `classes` ref to `teacher`
  backend/package.json
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/schemas/teacher.schema.ts
Labels: documentation, enhancement

#114 [Feature] add `classes` ref to `teacher`
  backend/package.json
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/schemas/teacher.schema.ts
Labels: enhancement

#115 Update: Release version 1.1.3 backend
  .github/workflows/pr-validation.yml
  backend/package.json
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/schemas/teacher.schema.ts
Labels: enhancement

#116 update: layout Footer & remove position fixed
  frontend/src/components/commons/Footer.tsx
Labels: enhancement

#119 update: footer layout
  frontend/src/components/commons/Footer.tsx
Labels: enhancement

#117 update layout footer
  frontend/src/components/commons/Footer.tsx
Labels: enhancement

#120 [Feature]change get by id to email for `student`
  backend/package.json
  backend/src/domains/students/students.controller.ts
  backend/src/domains/students/students.service.ts
Labels: enhancement

#121 [Feature]change get by id to email for `student `
  backend/package.json
  backend/src/domains/students/students.controller.ts
  backend/src/domains/students/students.service.ts
Labels: enhancement

#122 update: release version 1.1.4
  backend/package.json
  backend/src/domains/students/students.controller.ts
  backend/src/domains/students/students.service.ts
  frontend/src/components/commons/Footer.tsx
Labels: enhancement

#125 add: student login feature
  .github/workflows/commit-msg-validation.yml
  .github/workflows/pr-validation.yml
  .github/workflows/validate-branches-on-creation.yml
  backend/package.json
  backend/src/domains/students/students.controller.ts
  backend/src/domains/students/students.service.ts
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/teachers/teachers.service.ts
  backend/src/schemas/student.schema.ts
  backend/src/schemas/teacher.schema.ts
  frontend/src/App.tsx
  frontend/src/assets/styles/dropdownCenter.css
  frontend/src/assets/styles/header.css
  frontend/src/components/commons/Footer.tsx
  frontend/src/components/commons/Header.tsx
  frontend/src/components/student/DropdownCenter.tsx
  frontend/src/components/student/DropdownProfile.tsx
  frontend/src/components/student/Header.tsx
  frontend/src/components/student/LoginButton.tsx
  frontend/src/layouts/student.tsx
  frontend/src/layouts/student/notLogin.tsx
  frontend/src/pages/student/Homepage.tsx
  frontend/src/services/api/student.ts
  frontend/src/utils/jwtDecode.ts
  frontend/yarn.lock
  proxy/nginx.conf
Labels: enhancement

#128 update: content in login button
  frontend/src/components/student/LoginButton.tsx
Labels: enhancement

#129 update: pagekage json file
  frontend/package.json
  frontend/yarn.lock
Labels: enhancement

#131 update: default route
  frontend/src/App.tsx
Labels: enhancement

#126 add: login for `student` by Google
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/styles/dropdownCenter.css
  frontend/src/assets/styles/header.css
  frontend/src/components/commons/Footer.tsx
  frontend/src/components/commons/Header.tsx
  frontend/src/components/student/DropdownCenter.tsx
  frontend/src/components/student/DropdownProfile.tsx
  frontend/src/components/student/Header.tsx
  frontend/src/components/student/LoginButton.tsx
  frontend/src/layouts/student.tsx
  frontend/src/layouts/student/notLogin.tsx
  frontend/src/pages/student/Homepage.tsx
  frontend/src/services/api/student.ts
  frontend/src/utils/jwtDecode.ts
  frontend/yarn.lock
Labels: enhancement

#132 add: implement get teacher by email
  backend/package.json
  backend/src/domains/teachers/teachers.controller.ts
  backend/src/domains/teachers/teachers.service.ts
Labels: enhancement

#133 dev: release backend v1.1.5
  backend/package.json
  backend/src/domains/teachers/teachers.controller.ts
  backend/src/domains/teachers/teachers.service.ts
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/styles/dropdownCenter.css
  frontend/src/assets/styles/header.css
  frontend/src/components/commons/Footer.tsx
  frontend/src/components/commons/Header.tsx
  frontend/src/components/student/DropdownCenter.tsx
  frontend/src/components/student/DropdownProfile.tsx
  frontend/src/components/student/Header.tsx
  frontend/src/components/student/LoginButton.tsx
  frontend/src/layouts/student.tsx
  frontend/src/layouts/student/notLogin.tsx
  frontend/src/pages/student/Homepage.tsx
  frontend/src/services/api/student.ts
  frontend/src/utils/jwtDecode.ts
  frontend/yarn.lock
Labels: enhancement

#135 [Feature] update populate `classes` for `teacher` service
  backend/package.json
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/teachers/teachers.service.ts
Labels: enhancement

#136 [Feature] update populate `classes` for `teacher` service
  backend/package.json
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/teachers/teachers.service.ts
Labels: enhancement

#137 dev: release backend v1.1.6
  backend/package.json
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/teachers/teachers.service.ts
Labels: enhancement

#138 fix: fix teacher login
  backend/src/domains/teachers/teachers.service.ts
Labels: bug

#139 dev: release backend v1.1.7
  backend/package.json
  backend/src/domains/teachers/teachers.service.ts
Labels: bug, enhancement

#124 add: centers manager for admin
  backend/package.json
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/teachers/teachers.controller.ts
  backend/src/domains/teachers/teachers.service.ts
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/styles/dropdownCenter.css
  frontend/src/assets/styles/header.css
  frontend/src/assets/styles/listCenters.css
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/components/admin/Sidebar.tsx
  frontend/src/components/commons/Footer.tsx
  frontend/src/components/commons/Header.tsx
  frontend/src/components/commons/SIdebar.tsx
  frontend/src/components/student/DropdownCenter.tsx
  frontend/src/components/student/DropdownProfile.tsx
  frontend/src/components/student/Header.tsx
  frontend/src/components/student/LoginButton.tsx
  frontend/src/layouts/student.tsx
  frontend/src/layouts/student/notLogin.tsx
  frontend/src/pages/admin/CentersManagement.tsx
  frontend/src/pages/admin/Dashboard.tsx
  frontend/src/pages/student/Homepage.tsx
  frontend/src/services/api/student.ts
  frontend/src/utils/jwtDecode.ts
  frontend/yarn.lock
Labels: enhancement

#130 add: courses manager for admin
  backend/package.json
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/teachers/teachers.controller.ts
  backend/src/domains/teachers/teachers.service.ts
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/styles/dropdownCenter.css
  frontend/src/assets/styles/header.css
  frontend/src/assets/styles/listCourse.css
  frontend/src/components/admin/ListCourses.tsx
  frontend/src/components/admin/Sidebar.tsx
  frontend/src/components/commons/Footer.tsx
  frontend/src/components/commons/Header.tsx
  frontend/src/components/commons/SIdebar.tsx
  frontend/src/components/student/DropdownCenter.tsx
  frontend/src/components/student/DropdownProfile.tsx
  frontend/src/components/student/Header.tsx
  frontend/src/components/student/LoginButton.tsx
  frontend/src/layouts/student.tsx
  frontend/src/layouts/student/notLogin.tsx
  frontend/src/pages/admin/CoursesManagement.tsx
  frontend/src/pages/admin/Dashboard.tsx
  frontend/src/pages/student/Homepage.tsx
  frontend/src/services/api/student.ts
  frontend/src/utils/jwtDecode.ts
  frontend/yarn.lock
Labels: enhancement

#153 add: student profile page
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/commons/ProtectedRoute.tsx
  frontend/src/components/commons/SIdebar.tsx
  frontend/src/components/student/ButtonLogin.tsx
  frontend/src/components/student/DetailStudent.tsx
  frontend/src/components/student/DropdownProfile.tsx
  frontend/src/components/student/Sidebar.tsx
  frontend/src/layouts/student/student.haveSidebar.tsx
  frontend/src/layouts/student/student.noSidebar.tsx
  frontend/src/pages/student/Homepage.tsx
  frontend/src/pages/student/Login.tsx
  frontend/src/pages/student/Profile.tsx
  frontend/src/services/custom/getStudentbyToken.ts
  frontend/src/utils/dateFormat.ts
  frontend/yarn.lock
Labels: enhancement

#155 add: student profile page
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/commons/ProtectedRoute.tsx
  frontend/src/components/commons/SIdebar.tsx
  frontend/src/components/student/ButtonLogin.tsx
  frontend/src/components/student/DetailStudent.tsx
  frontend/src/components/student/DropdownProfile.tsx
  frontend/src/components/student/Sidebar.tsx
  frontend/src/layouts/student/student.haveSidebar.tsx
  frontend/src/layouts/student/student.noSidebar.tsx
  frontend/src/pages/student/Homepage.tsx
  frontend/src/pages/student/Login.tsx
  frontend/src/pages/student/Profile.tsx
  frontend/src/services/custom/getStudentbyToken.ts
  frontend/src/utils/dateFormat.ts
  frontend/yarn.lock
Labels: enhancement

#165 fix: resolve conflict
  frontend/src/App.tsx
  frontend/src/components/admin/AdminHeader.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/components/admin/ProtectedRoute.tsx
  frontend/src/components/student/Sidebar.tsx
  frontend/src/components/teacher/Sidebar.tsx
  frontend/src/components/teacher/TeacherDropdown.tsx
  frontend/src/layouts/teacher.tsx
Labels: bug, enhancement

#166 fix: resolve conflict
  frontend/src/App.tsx
  frontend/src/components/admin/AdminHeader.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/components/admin/ProtectedRoute.tsx
  frontend/src/components/student/Sidebar.tsx
  frontend/src/components/teacher/Sidebar.tsx
  frontend/src/components/teacher/TeacherDropdown.tsx
  frontend/src/layouts/teacher.tsx
Labels: bug, enhancement

#168 fix: bug release
  frontend/src/App.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/components/admin/ListCourses.tsx
  frontend/src/layouts/admin.tsx
  frontend/src/layouts/teacher.tsx
  frontend/src/pages/teacher/Classes.tsx
  frontend/src/pages/teacher/ListClass.tsx
Labels: bug

#169 fix: bug release
  frontend/src/App.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/components/admin/ListCourses.tsx
  frontend/src/layouts/admin.tsx
  frontend/src/layouts/teacher.tsx
  frontend/src/pages/teacher/Classes.tsx
  frontend/src/pages/teacher/ListClass.tsx
Labels: bug

#171 dev: release frontend v1.0.0 again again
  .github/workflows/build-backend.yml
  .github/workflows/build-frontend.yml
  .github/workflows/publish-backend-image.yml
  .github/workflows/publish-frontend-image.yml
  frontend/src/components/commons/Sidebar.tsx
Labels: bug, enhancement

#172 [Feature] add api get by Id for `student`
  backend/src/domains/students/students.controller.ts
  backend/src/domains/students/students.service.ts
Labels: enhancement

#173 [Feature] add api get by Id for `student`
  backend/src/domains/students/students.controller.ts
  backend/src/domains/students/students.service.ts
Labels: enhancement

#174 dev: release backend v1.1.8
  backend/package.json
Labels: enhancement

#175 dev: release backend v1.1.8
  backend/package.json
Labels: enhancement

#183 [Feature] implement `vouchers` list for `admin` manager
  frontend/src/App.tsx
  frontend/src/components/admin/ListVouchers.tsx
  frontend/src/components/admin/Sidebar.tsx
  frontend/src/pages/admin/VouchersManagement.tsx
  frontend/src/utils/dateFormat.ts
Labels: enhancement

#194 add: change for ListClass
  frontend/src/components/teacher/ListClass.tsx
  frontend/src/components/teacher/ListStudent.tsx
  frontend/src/pages/teacher/Classes.tsx
Labels: enhancement

#192 update: format again list `voucher` for `admin`
  frontend/src/components/admin/ListVouchers.tsx
Labels: enhancement

#190 [Feature] implement `voucher` detail page for `admin`
  frontend/src/App.tsx
  frontend/src/components/admin/ListVouchers.tsx
  frontend/src/components/admin/VoucherDetail.tsx
  frontend/src/pages/admin/VoucherDetail.tsx
  frontend/src/services/api/voucher.ts
Labels: enhancement

#195 add: class list for student
  frontend/src/App.tsx
  frontend/src/components/commons/ButtonGoback.tsx
  frontend/src/components/student/DetailStudent.tsx
  frontend/src/components/student/ListClass.tsx
  frontend/src/components/student/Sidebar.tsx
  frontend/src/layouts/student/student.haveSidebar.tsx
  frontend/src/pages/student/ClassList.tsx
  frontend/src/pages/student/Profile.tsx
  frontend/src/services/api/class.ts
Labels: enhancement

#196 Feature/get class by course id chuong
  backend/package.json
  backend/src/domains/classes/classes.controller.ts
  backend/src/domains/classes/classes.service.ts
  backend/src/domains/classes/dto/class.dto.ts
Labels: enhancement

#197 Feature/get class by course
  backend/package.json
  backend/src/domains/classes/classes.controller.ts
  backend/src/domains/classes/classes.service.ts
  backend/src/domains/classes/dto/class.dto.ts
Labels: enhancement

#199 update: student home page
  frontend/src/components/student/ButtonLogin.tsx
  frontend/src/layouts/student/student.noSidebar.tsx
  frontend/src/pages/student/Homepage.tsx
Labels: enhancement

#200 update: student home page
  frontend/src/components/student/ButtonLogin.tsx
  frontend/src/layouts/student/student.noSidebar.tsx
  frontend/src/pages/student/Homepage.tsx
Labels: enhancement

#202 add: add course detail for admin
  frontend/src/App.tsx
  frontend/src/components/admin/DetailOfCourse.tsx
  frontend/src/components/admin/ListCourses.tsx
  frontend/src/pages/admin/CourseDetail.tsx
  frontend/src/services/api/course.ts
Labels: enhancement

#203 add: add course detail for admin
  frontend/src/App.tsx
  frontend/src/components/admin/DetailOfCourse.tsx
  frontend/src/components/admin/ListCourses.tsx
  frontend/src/pages/admin/CourseDetail.tsx
  frontend/src/services/api/course.ts
Labels: enhancement

#218 update: dropdown center
  frontend/src/assets/styles/dropdownCenter.css
  frontend/src/components/student/CardCourse.tsx
  frontend/src/components/student/DropdownCenter.tsx
  frontend/src/components/student/ListCourse.tsx
  frontend/src/layouts/student/student.noSidebar.tsx
  frontend/src/main.tsx
Labels: enhancement

#219 update: dropdown center
  frontend/src/assets/styles/dropdownCenter.css
  frontend/src/components/student/CardCourse.tsx
  frontend/src/components/student/DropdownCenter.tsx
  frontend/src/components/student/ListCourse.tsx
  frontend/src/layouts/student/student.noSidebar.tsx
  frontend/src/main.tsx
Labels: enhancement

#243 Feature/fix api chuong
  backend/package.json
  backend/src/domains/centers/dto/center.dto.ts
  backend/src/domains/classes/dto/class.dto.ts
  backend/src/domains/payments/dto/payment.dto.ts
  backend/src/domains/slots/dto/slot.dto.ts
  backend/src/domains/students/dto/student.dto.ts
  backend/src/schemas/class.schema.ts
Labels: enhancement

#245 Feature/fix api
  backend/package.json
  backend/src/domains/centers/dto/center.dto.ts
  backend/src/domains/classes/dto/class.dto.ts
  backend/src/domains/payments/dto/payment.dto.ts
  backend/src/domains/slots/dto/slot.dto.ts
  backend/src/domains/students/dto/student.dto.ts
  backend/src/schemas/class.schema.ts
Labels: enhancement

#242 update: center information for admin
  frontend/src/App.tsx
  frontend/src/components/admin/FormEditCenter.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/layouts/admin.tsx
  frontend/src/layouts/student/student.noSidebar.tsx
  frontend/src/pages/admin/CenterEdit.tsx
  frontend/src/services/api/center.ts
  frontend/src/slices/center.ts
Labels: enhancement

#248 update: alias for import path
  frontend/src/components/admin/FormEditCenter.tsx
Labels: bug

#247 add: update center page for admin
  frontend/src/App.tsx
  frontend/src/components/admin/FormEditCenter.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/layouts/admin.tsx
  frontend/src/layouts/student/student.noSidebar.tsx
  frontend/src/pages/admin/CenterEdit.tsx
  frontend/src/services/api/center.ts
  frontend/src/slices/center.ts
Labels: enhancement

#188 add: center detail for admin
  frontend/src/App.tsx
  frontend/src/components/admin/DetailOfCenter.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/pages/admin/CenterDetail.tsx
  frontend/src/services/api/center.ts
Labels: enhancement

#239 add: center create for admin
  frontend/src/App.tsx
  frontend/src/components/admin/FormCreateCenter.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/pages/admin/CenterCreate.tsx
  frontend/src/services/api/center.ts
  frontend/src/services/api/class.ts
Labels: enhancement

#251 [Feature] center detail for admin (@yuhtnguyen)
  frontend/src/App.tsx
  frontend/src/components/admin/DetailOfCenter.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/pages/admin/CenterDetail.tsx
  frontend/src/services/api/center.ts
Labels: enhancement

#252 [Feature] center create for admin [@yuhtnguyen]
  frontend/src/App.tsx
  frontend/src/components/admin/FormCreateCenter.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/pages/admin/CenterCreate.tsx
  frontend/src/services/api/center.ts
  frontend/src/services/api/class.ts
Labels: enhancement

#253 [Feature] student detail for teacher (@linhlm0210)
  frontend/src/App.tsx
  frontend/src/components/teacher/ListStudent.tsx
  frontend/src/components/teacher/StudentDetail.tsx
  frontend/src/pages/teacher/StudentDetail.tsx
Labels: enhancement

#257 [Feature] create voucher chuong
  backend/package.json
  backend/src/domains/centers/dto/center.dto.ts
  backend/src/domains/classes/dto/class.dto.ts
  backend/src/domains/payments/dto/payment.dto.ts
  backend/src/domains/slots/dto/slot.dto.ts
  backend/src/domains/students/dto/student.dto.ts
  backend/src/schemas/class.schema.ts
  frontend/src/App.tsx
  frontend/src/components/admin/FormCreateVoucher.tsx
  frontend/src/components/admin/FormEditCenter.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/components/admin/ListVouchers.tsx
  frontend/src/components/admin/VoucherDetail.tsx
  frontend/src/components/student/ButtonLogin.tsx
  frontend/src/components/student/CardCourse.tsx
  frontend/src/components/student/CourseDetail.tsx
  frontend/src/layouts/admin.tsx
  frontend/src/layouts/student/student.noSidebar.tsx
  frontend/src/pages/admin/CenterEdit.tsx
  frontend/src/pages/admin/VoucherCreate.tsx
  frontend/src/pages/student/CourseDetail.tsx
  frontend/src/services/api/center.ts
  frontend/src/services/api/voucher.ts
  frontend/src/slices/center.ts
  frontend/src/utils/inputValidate.ts
Labels: enhancement

#258 [Feature] implement create `voucher` page for `admin`
  frontend/src/App.tsx
  frontend/src/components/admin/FormCreateVoucher.tsx
  frontend/src/components/admin/ListVouchers.tsx
  frontend/src/components/admin/VoucherDetail.tsx
  frontend/src/components/student/ButtonLogin.tsx
  frontend/src/pages/admin/VoucherCreate.tsx
  frontend/src/services/api/voucher.ts
  frontend/src/utils/inputValidate.ts
Labels: enhancement

#260 add: edit course page for admin
  frontend/src/App.tsx
  frontend/src/components/admin/DetailOfCenter.tsx
  frontend/src/components/admin/DetailOfCourse.tsx
  frontend/src/components/admin/FormCreateCourse.tsx
  frontend/src/components/admin/FormEditCenter.tsx
  frontend/src/components/admin/FormEditCourse.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/components/admin/ListCourses.tsx
  frontend/src/components/admin/ListVouchers.tsx
  frontend/src/components/teacher/ListClass.tsx
  frontend/src/components/teacher/ListStudent.tsx
  frontend/src/components/teacher/StudentDetail.tsx
  frontend/src/pages/admin/CourseCreate.tsx
  frontend/src/pages/admin/CourseEdit.tsx
  frontend/src/services/api/course.ts
  frontend/src/slices/course.ts
  frontend/src/utils/inputValidate.ts
Labels: enhancement

#256 add: view list courses and list vouchers in center for admin
  frontend/src/App.tsx
  frontend/src/pages/admin/ListCoursesCenter.tsx
  frontend/src/pages/admin/ListVouchersCenter.tsx
  frontend/src/services/api/center.ts
Labels: enhancement

#265 add: view course voucher detail in center
  frontend/src/App.tsx
  frontend/src/pages/admin/ListCoursesCenter.tsx
  frontend/src/pages/admin/ListVouchersCenter.tsx
  frontend/src/services/api/center.ts
Labels: enhancement

#264 add: update course detail for admin
  frontend/src/App.tsx
  frontend/src/components/admin/DetailOfCenter.tsx
  frontend/src/components/admin/DetailOfCourse.tsx
  frontend/src/components/admin/FormCreateCourse.tsx
  frontend/src/components/admin/FormEditCenter.tsx
  frontend/src/components/admin/FormEditCourse.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/components/admin/ListCourses.tsx
  frontend/src/components/admin/ListVouchers.tsx
  frontend/src/components/teacher/ListClass.tsx
  frontend/src/components/teacher/ListStudent.tsx
  frontend/src/components/teacher/StudentDetail.tsx
  frontend/src/pages/admin/CourseCreate.tsx
  frontend/src/pages/admin/CourseEdit.tsx
  frontend/src/services/api/course.ts
  frontend/src/slices/course.ts
  frontend/src/utils/inputValidate.ts
Labels: enhancement

#270 add: add profile page for teacher
  frontend/src/App.tsx
  frontend/src/components/teacher/DetailTeacher.tsx
  frontend/src/pages/teacher/Classes.tsx
  frontend/src/pages/teacher/Profile.tsx
  frontend/src/services/api/teacher.ts
  frontend/src/services/custom/getTeacherbyToken.ts
Labels: enhancement

#268 add attendances report for student
  frontend/src/App.tsx
  frontend/src/components/student/AttendencesReport.tsx
  frontend/src/pages/student/AttendencesReport.tsx
  frontend/src/utils/dateFormat.ts
Labels: enhancement

#273 [Feature] format admin page
  frontend/src/components/admin/AdminHeader.tsx
  frontend/src/components/admin/CenterDetail.tsx
  frontend/src/components/admin/FormCreateCenter.tsx
  frontend/src/components/admin/FormCreateCourse.tsx
  frontend/src/components/admin/FormCreateVoucher.tsx
  frontend/src/components/admin/FormEditCenter.tsx
  frontend/src/components/admin/FormEditCourse.tsx
  frontend/src/components/admin/FormEditVoucher.tsx
  frontend/src/components/admin/ListCenters.tsx
  frontend/src/components/admin/ListCourses.tsx
  frontend/src/components/admin/VoucherDetail.tsx
  frontend/src/pages/admin/CenterCreate.tsx
  frontend/src/utils/formatPrice.ts
Labels: enhancement

#276 update: sort route for app
  frontend/src/App.tsx
  frontend/src/pages/admin/ListCoursesOfCenter.tsx
  frontend/src/pages/admin/ListVouchersOfCenter.tsx
Labels: enhancement

#277 fix: error build frontend
  frontend/src/App.tsx
  frontend/src/pages/admin/ListTeacerOfCenter.tsx
Labels: enhancement

#278 fix err build frontend
  frontend/src/App.tsx
  frontend/src/pages/admin/ListTeacerOfCenter.tsx
Labels: enhancement

#279 fix: fix update teacher with password
  backend/package.json
  backend/src/domains/teachers/teachers.service.ts
Labels: bug

#283 dev: release backend v1.2.2
  backend/package.json
  backend/src/domains/teachers/teachers.service.ts
Labels: enhancement

#284 dev: release backend v1.2.3
  backend/package.json
  backend/src/domains/admins/admins.controller.ts
  backend/src/domains/admins/admins.service.ts
  backend/src/domains/admins/dto/admin.dto.ts
  backend/src/domains/teachers/dto/teacher.dto.ts
  backend/src/domains/teachers/teachers.controller.ts
  backend/src/domains/teachers/teachers.service.ts
  frontend/src/App.tsx
  frontend/src/components/admin/ClassDetailOfCenter.tsx
  frontend/src/components/admin/ListClassOfCenter.tsx
  frontend/src/components/admin/ListTeacherOfCenter.tsx
  frontend/src/components/admin/TeacherDetailOfCenter.tsx
  frontend/src/pages/admin/ClassDetail.tsx
  frontend/src/pages/admin/ListTeacherOfCenter.tsx
  frontend/src/pages/admin/TeacherDetail.tsx
  frontend/src/services/api/teacher.ts
Labels: enhancement

#288 Payment history and payment history detail for student
  frontend/src/App.tsx
  frontend/src/components/student/PaymentDetail.tsx
  frontend/src/components/student/PaymentHistory.tsx
  frontend/src/pages/student/PaymentDetail.tsx
  frontend/src/pages/student/PaymentHistory.tsx
  frontend/src/services/api/payment.ts
  frontend/src/services/api/student.ts
  frontend/src/services/api/teacher.ts
Labels: enhancement

#282 add: add update profile and change password
  frontend/src/App.tsx
  frontend/src/components/teacher/ChangePasswordForm.tsx
  frontend/src/components/teacher/DetailTeacher.tsx
  frontend/src/components/teacher/FormUpdateProfile.tsx
  frontend/src/components/teacher/TeacherDropdown.tsx
  frontend/src/pages/teacher/ChangePassword.tsx
  frontend/src/pages/teacher/EditProfile.tsx
  frontend/src/pages/teacher/Login.tsx
  frontend/src/services/api/teacher.ts
  frontend/src/slices/teacher.ts
Labels: enhancement

#297 add: teacher schedule page
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/styles/schedule.css
  frontend/src/components/teacher/DropdownCenter.tsx
  frontend/src/components/teacher/DropdownCourse.tsx
  frontend/src/components/teacher/Schedule.tsx
  frontend/src/components/teacher/Sidebar.tsx
  frontend/src/main.tsx
  frontend/src/pages/teacher/ScheduleView.tsx
  frontend/src/services/api/center.ts
  frontend/src/services/api/slot.ts
  frontend/src/services/api/teacher.ts
  frontend/src/utils/dateFormat.ts
  frontend/yarn.lock
Labels: enhancement

#292 add: add update profile and change password
  frontend/src/App.tsx
  frontend/src/components/teacher/ChangePasswordForm.tsx
  frontend/src/components/teacher/DetailTeacher.tsx
  frontend/src/components/teacher/FormUpdateProfile.tsx
  frontend/src/components/teacher/TeacherDropdown.tsx
  frontend/src/pages/teacher/ChangePassword.tsx
  frontend/src/pages/teacher/EditProfile.tsx
  frontend/src/pages/teacher/Login.tsx
  frontend/src/services/api/teacher.ts
  frontend/src/slices/teacher.ts
Labels: enhancement

#305 [Feature] implement change password page for admin
  frontend/src/App.tsx
  frontend/src/components/admin/FormChangePassword.tsx
  frontend/src/components/admin/SetupSchedules.tsx
  frontend/src/components/admin/Sidebar.tsx
  frontend/src/pages/admin/ChangePassword.tsx
  frontend/src/pages/admin/ListClass.tsx
  frontend/src/pages/admin/SchedulesManagement.tsx
  frontend/src/services/api/admin.ts
Labels: enhancement

#307 [Feature] implement change password page for admin
  frontend/src/App.tsx
  frontend/src/components/admin/FormChangePassword.tsx
  frontend/src/components/admin/SetupSchedules.tsx
  frontend/src/components/admin/Sidebar.tsx
  frontend/src/pages/admin/ChangePassword.tsx
  frontend/src/pages/admin/ListClass.tsx
  frontend/src/pages/admin/SchedulesManagement.tsx
  frontend/src/services/api/admin.ts
Labels: enhancement

#309 [Feature] implement `createAttendancesForSlot` & `updateAttendancecheck` api
  backend/package.json
  backend/src/domains/attendances/attendances.controller.ts
  backend/src/domains/attendances/attendances.module.ts
  backend/src/domains/attendances/attendances.service.ts
Labels: enhancement

#310 [Feature] implement api to create & check attendances
  backend/package.json
  backend/src/domains/attendances/attendances.controller.ts
  backend/src/domains/attendances/attendances.module.ts
  backend/src/domains/attendances/attendances.service.ts
Labels: enhancement

#313 feat: backend implement zalopay
  backend/package.json
  backend/src/domains/payments/payments.controller.ts
  backend/src/domains/payments/payments.module.ts
  backend/src/domains/payments/payments.service.ts
  backend/src/domains/payments/zalopay/config/zalopay.config.ts
  backend/src/domains/payments/zalopay/dto/zalopay.dto.ts
  backend/src/domains/payments/zalopay/zalopay.module.ts
  backend/src/domains/payments/zalopay/zalopay.service.ts
  backend/yarn.lock
Labels: documentation, enhancement

#314 feat: backend implement zalopay
  backend/package.json
  backend/src/domains/payments/payments.controller.ts
  backend/src/domains/payments/payments.module.ts
  backend/src/domains/payments/payments.service.ts
  backend/src/domains/payments/zalopay/config/zalopay.config.ts
  backend/src/domains/payments/zalopay/dto/zalopay.dto.ts
  backend/src/domains/payments/zalopay/zalopay.module.ts
  backend/src/domains/payments/zalopay/zalopay.service.ts
  backend/yarn.lock
Labels: enhancement

#315 dev: release backend v1.3.0
  backend/package.json
  backend/src/domains/payments/payments.controller.ts
  backend/src/domains/payments/payments.module.ts
  backend/src/domains/payments/payments.service.ts
  backend/src/domains/payments/zalopay/config/zalopay.config.ts
  backend/src/domains/payments/zalopay/dto/zalopay.dto.ts
  backend/src/domains/payments/zalopay/zalopay.module.ts
  backend/src/domains/payments/zalopay/zalopay.service.ts
  backend/yarn.lock
Labels: enhancement

#321 Feature/fix slot api chuong
  backend/package.json
  backend/src/domains/attendances/attendances.module.ts
  backend/src/domains/attendances/attendances.service.ts
  backend/src/domains/slots/dto/slot.dto.ts
Labels: enhancement

#329 Feature/check attendances chuong
  frontend/src/App.tsx
  frontend/src/components/teacher/FormCheckAttendances.tsx
  frontend/src/components/teacher/Schedule.tsx
  frontend/src/pages/teacher/CheckAttendances.tsx
  frontend/src/schemas/attendance.schema.ts
  frontend/src/services/api/attendance.ts
  frontend/src/services/api/slot.ts
Labels: enhancement

#330 [Feature] implement check attendances page for teacher
  frontend/src/App.tsx
  frontend/src/components/teacher/FormCheckAttendances.tsx
  frontend/src/components/teacher/Schedule.tsx
  frontend/src/pages/teacher/CheckAttendances.tsx
  frontend/src/schemas/attendance.schema.ts
  frontend/src/services/api/attendance.ts
  frontend/src/services/api/slot.ts
Labels: enhancement

#333 feat: implement momo payment
  backend/src/domains/payments/momo/config/momo.config.ts
  backend/src/domains/payments/momo/dto/momo.dto.ts
  backend/src/domains/payments/momo/momo.module.ts
  backend/src/domains/payments/momo/momo.service.ts
  backend/src/domains/payments/payments.controller.ts
  backend/src/domains/payments/payments.module.ts
  backend/src/domains/payments/payments.service.ts
  backend/src/domains/payments/zalopay/config/zalopay.config.ts
Labels: enhancement

#334 feat: momo payment
  backend/src/domains/payments/momo/config/momo.config.ts
  backend/src/domains/payments/momo/dto/momo.dto.ts
  backend/src/domains/payments/momo/momo.module.ts
  backend/src/domains/payments/momo/momo.service.ts
  backend/src/domains/payments/payments.controller.ts
  backend/src/domains/payments/payments.module.ts
  backend/src/domains/payments/payments.service.ts
  backend/src/domains/payments/zalopay/config/zalopay.config.ts
Labels: enhancement

#335 dev: release backend v1.3.2
  backend/package.json
  backend/src/domains/payments/momo/config/momo.config.ts
  backend/src/domains/payments/momo/dto/momo.dto.ts
  backend/src/domains/payments/momo/momo.module.ts
  backend/src/domains/payments/momo/momo.service.ts
  backend/src/domains/payments/payments.controller.ts
  backend/src/domains/payments/payments.module.ts
  backend/src/domains/payments/payments.service.ts
  backend/src/domains/payments/zalopay/config/zalopay.config.ts
Labels: enhancement

#338 Feature/caculate salary chuong
  backend/package.json
  backend/src/domains/attendances/attendances.module.ts
  backend/src/domains/classes/classes.controller.ts
  backend/src/domains/classes/classes.module.ts
  backend/src/domains/classes/classes.service.ts
  backend/src/domains/salaries/dto/salary.dto.ts
  backend/src/domains/salaries/salaries.controller.ts
  backend/src/domains/salaries/salaries.module.ts
  backend/src/domains/salaries/salaries.service.ts
  backend/src/domains/slots/slots.module.ts
  backend/src/domains/slots/slots.service.ts
  frontend/src/App.tsx
  frontend/src/components/admin/FormSalariesCalculate.tsx
  frontend/src/components/admin/ListSalaries.tsx
  frontend/src/components/admin/Sidebar.tsx
  frontend/src/pages/admin/Dashboard.tsx
  frontend/src/pages/admin/SalariesCreate.tsx
  frontend/src/pages/admin/SalariesManagement.tsx
  frontend/src/services/api/salary.ts
Labels: enhancement

#343 [Feature] implement page caculate salary
  backend/package.json
  backend/src/domains/slots/slots.service.ts
  frontend/src/components/admin/FormCalculateSalaries.tsx
  frontend/src/components/admin/FormSalariesCalculate.tsx
  frontend/src/components/admin/ListSalaries.tsx
  frontend/src/pages/admin/SalariesCreate.tsx
  frontend/src/schemas/salary.schema.ts
  frontend/src/services/api/class.ts
  frontend/src/services/api/salary.ts
Labels: enhancement
